###############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and RADIUSS
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
###############################################################################

stages:
  - first
  - second
  - third

default:
  tags: [shell, ruby]

status-pending:
  stage: first
  script:
    - report-status ${CONTEXT} pending

child-job:
  stage: second
  script:
    - echo -e "Hello sub-World, I will fail the tests."
    - sleep ${DURATION}
    - exit 1

status-success:
  stage: third
  script:
    - report-status ${CONTEXT} success
  when: on_success

status-failure:
  stage: third
  script:
    - report-status ${CONTEXT} failure
  when: on_failure
