#!/bin/bash

context=${1}
commit_status=${2}

curl --url "https://api.github.com/repos/adrienbernede/ChildPipelineReports/statuses/${CI_COMMIT_SHA}" \
     --header 'Content-Type: application/json' \
     --header "authorization: Bearer ${GITHUB_TOKEN}" \
     --data "{ \"state\": \"${commit_status}\", \"target_url\": \"${CI_PIPELINE_URL}\", \"description\": \"All Gitlab pipelines\", \"context\": \"ci/gitlab/${context}\" }"

